### ISSUE TITLE
Integrating with `pre-commit.com`

### ISSUE THREAD

**Issue by LecrisUT** [typicode/husky#1391]
I thought there was already an issue about this, but I can't find it, so I am creating one again.

The issue over here is how to satisfy both workflows? `pre-commit.com` is generally more robust in how it selects the pre-commits run and how it is customizable on the `pre-commit`, `pre-push` etc. But than husky is more manageable in that it can run simple shell scripts, the main use-case I have is to check github action `dist` folder.

One suggestion is to make `husky` executable as `.pre-commit-hooks.yaml`. Pre-commit already [supports node](https://pre-commit.com/#node) environments, something like:
```yaml
-   id: husky
    name: Husky pre-commit
    description: Run husky defined pre-commits
    entry: husky
    language: node
```
