### ISSUE TITLE
Cannot install husky in docker on Circle CI

### ISSUE THREAD

**Issue by Siegrift** [typicode/husky#495]
This is my circle ci config:
```yml
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:chakracore-10.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # run tests!
      - run: yarn test
```

and this is the error I am getting on circle CI

```
#!/bin/bash -eo pipefail
yarn install --frozen-lockfile
yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/circleci/repo/node_modules/husky: Command failed.
Exit code: 1
Command: node husky install
Arguments: 
Directory: /home/circleci/repo/node_modules/husky
Output:
/home/circleci/repo/node_modules/pkg-dir/node_modules/find-up/index.js:28
		const foundPath = await runMatcher({...options, cwd: directory});
		                                    ^^^^

SyntaxError: Expected identifier, string or number
   at Script (vm.js:87:7)
   at createScript (vm.js:251:3)
   at runInThisContext (vm.js:303:3)
   at Module.prototype._compile (internal/modules/cjs/loader.js:656:3)
   at Module._extensions[.js] (internal/modules/cjs/loader.js:699:3)
   at Module.prototype.load (internal/modules/cjs/loader.js:598:3)
   at tryModuleLoad (internal/modules/cjs/loader.js:537:5)
   at Module._load (internal/modules/cjs/loader.js:529:3)
   at Module.prototype.require (internal/modules/cjs/loader.js:636:3)
   at require (internal/modules/cjs/helpers.js:20:7)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code 1
```

My package json look like this:
```json
{
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@types/jest": "^24.0.13",
    "@types/node": "^12.0.2",
    "husky": "^2.3.0",
    "jest": "^24.8.0",
    "ts-jest": "^24.0.2",
    "tslint": "^5.16.0",
    "tslint-config-prettier": "^1.18.0",
    "tslint-config-standard": "^8.0.1",
    "typescript": "^3.4.5"
  },
  "scripts": {
    "test": "jest",
    "test-watch": "jest --watch"
  },
  "husky": {
    "hooks": {
      "pre-push": "yarn test"
    }
  }
}
```
